/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_peromsik_hebcal_HebcalNativeLoader */

#ifndef _Included_net_peromsik_hebcal_HebcalNativeLoader
#define _Included_net_peromsik_hebcal_HebcalNativeLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_peromsik_hebcal_HebcalNativeLoader
 * Method:    hebcal_set_date
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_peromsik_hebcal_HebcalNativeLoader_hebcal_1set_1date
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     net_peromsik_hebcal_HebcalNativeLoader
 * Method:    hebcal_set_prefs
 * Signature: (ZZZ)V
 */
JNIEXPORT void JNICALL Java_net_peromsik_hebcal_HebcalNativeLoader_hebcal_1set_1prefs
  (JNIEnv *, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     net_peromsik_hebcal_HebcalNativeLoader
 * Method:    hebcal_range_events
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_peromsik_hebcal_HebcalNativeLoader_hebcal_1range_1events
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_peromsik_hebcal_HebcalNativeLoader
 * Method:    hebcal_get_cities
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_peromsik_hebcal_HebcalNativeLoader_hebcal_1get_1cities
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
